version: "3.8"
services:
  gpu-jupyter:
    container_name: ml-base
    shm_size: 8gb
    restart: unless-stopped
    build: .build
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    volumes:
      - /home/surajt/projects/fastbook:/home/jovyan/work
      - /home/surajt/.fastai:/home/jovyan/.fastai
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
      NB_UID: ${JUPYTER_UID:-1000}
      NB_GID: ${JUPYTER_GID:-1000}
    # enable sudo permissions
    user:
      "root"

networks:
  default:
    external: true
    name: nexus
